modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Hand%20Over%20Your%20Items"
logoFile="icon.png"

[[mods]]
modId="handoveryouritems"
version="3.0"
displayName="Hand Over Your Items"
displayURL="https://curseforge.com/minecraft/mc-mods/hand-over-your-items"
authors="Rick South"
description='''Adds to ability to give other players items in a server without dropping them on the floor.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  
Adam E, Alister, aternosorg, Cherriesaurus, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Robert Gilbert, Shana Gitnick, Sija, Tyler Behl, Wendi S   
If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.handoveryouritems]]
    modId="collective"
    mandatory=true
    versionRange="[6.18,)"
    ordering="NONE"
    side="BOTH"